Term 20
everypolitician-scrapers/korean-assembly-members-wikidata pull request #1
Opened 2016-10-11 15:24 UTC by chrismytton

This adds term 20 information from [this page](https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD_%EC%A0%9C20%EB%8C%80_%EA%B5%AD%ED%9A%8C%EC%9D%98%EC%9B%90_%EB%AA%A9%EB%A1%9D).

Part of https://github.com/everypolitician/everypolitician-data/issues/18448

2016-10-11 15:32 UTC, tmtmtmtm requested changes

2016-10-11 15:32 UTC, tmtmtmtm commented on scraper.rb
> +EveryPolitician::Wikidata.scrape_wikidata(names: { ko: names_19 + names_20 }, output: false)
Tiniest of tiny nits, but probably a little better to make that `names_19 | names_20` as we expect there'll be some overlap there.

2016-10-11 15:32 UTC, tmtmtmtm commented on scraper.rb
> +warn EveryPolitician::Wikidata.notify_rebuilder
We should really replace this with a webhook call now

2016-10-11 15:58 UTC, chrismytton commented on scraper.rb
> +EveryPolitician::Wikidata.scrape_wikidata(names: { ko: names_19 + names_20 }, output: false)
Done in https://github.com/everypolitician-scrapers/korean-assembly-members-wikidata/pull/1/commits/4aaae59de5e3509dd13bec9719d9000620ff534f

2016-10-11 15:59 UTC, chrismytton commented on scraper.rb
> +warn EveryPolitician::Wikidata.notify_rebuilder
Good idea. I've removed the notifier code in https://github.com/everypolitician-scrapers/korean-assembly-members-wikidata/pull/1/commits/7dc85198aa22b717248964bbfb178b7f86ac8838. Can you update https://morph.io/tmtmtmtm/korean-assembly-members-wikidata and move the environment variable to be a webhook please?

2016-10-11 15:59 UTC, chrismytton commented
@tmtmtmtm 👀

2016-10-12 21:49 UTC, tmtmtmtm approved these changes

2016-10-12 21:50 UTC, tmtmtmtm commented on scraper.rb
> +warn EveryPolitician::Wikidata.notify_rebuilder
Done, though the general pattern for scrapers that can be moved safely (e.g. Wikidata ones where we clean out the database on every run anyway) is to just make a new everypolitician-scrapers version and then remove the personal version.

2016-10-12 21:50 UTC, merged

2016-10-12 21:51 UTC, tmtmtmtm commented
👍  — I've also triggered a new run of the scraper post-merge.